### ISSUE TITLE
Stop compiling FreeSwitch - use RPMs

### ISSUE THREAD

**Issue by xrobau** [iNextrix/ASTPP#358]
I find it odd that you're installing the freeswitch repo, but not using their RPMS. 

Here's the list of RPMs I've been using in my playbook to create a Freeswitch server (note that this is excessive, but is a good starting point)

```
- name: Install freeswitch bits and pieces
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - git
    - php56w
    - php56w-cli
    - php56w-fpm
    - php56w-mcrypt
    - php56w-devel
    - php56w-common
    - php56w-cli
    - php56w-gd
    - php56w-pear
    - php56w-mysql
    - php56w-pdo
    - php56w-pecl-json
    - mysql
    - ntp
    - screen
    - bzip2
    - curl
    - dmidecode
    - make
    - unixODBC
    - zlib
    - bc
    - libvpx2*
    - libdb4*
    - lua
    - freeswitch
    - freeswitch-config-vanilla
    - freeswitch-xml-curl
    - freeswitch-application-lcr
    - freeswitch-application-hash
    - freeswitch-lua
    - freeswitch-event-json-cdr
    - freeswitch-sounds-music
    - freeswitch-sounds-music-16000.noarch
    - freeswitch-sounds-music-32000.noarch
    - freeswitch-sounds-music-48000.noarch
    - freeswitch-sounds-music-8000.noarch
    - freeswitch-sounds-en-us-callie.noarch
    - freeswitch-sounds-en-us-callie-16000.noarch
    - freeswitch-sounds-en-us-callie-32000.noarch
    - freeswitch-sounds-en-us-callie-48000.noarch
    - freeswitch-sounds-en-us-callie-8000.noarch
    - cpio
    - unixODBC
    - mysql-connector-odbc
    - libxml2
    - openssl
```
